[package]
name = "opening-hours-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "*"
opening-hours = { version = "*", features = ["auto-country", "auto-timezone"] }
wasm-logger = "0.2.0"
web-sys = "0.3.77"
yew = { version = "*", features = ["csr"] }
